### ISSUE TITLE
Incorrect CORS Documentation

### ISSUE THREAD

**Issue by rdegges** [okta/okta.github.io#1016]
The documentation on our Enabling Cors guide is incorrect, eg: https://developer.okta.com/docs/api/getting_started/enabling_cors.html#granting-cross-origin-access-to-websites

It refers to things as CORS (vs Trusted Origins), has outdated screenshots, etc.

This is referred to by our widget documentation which is probably used quite often, so we should get that fixed asap.

**Comment by jakubvul-okta** [comment]
My solution here is to change the link:

> follow the steps found under the "Trusted Origins tab" section in our [API Security help page](https://help.okta.com/en/prev/Content/Topics/Security/API.htm).
