### ISSUE TITLE
Widget Docs Duplicate CORS Information

### ISSUE THREAD

**Issue by rdegges** [okta/okta.github.io#1017]
In our widget guide, https://developer.okta.com/code/javascript/okta_sign-in_widget.html there is duplicated information about CORS.

Up in intro, we introduce CORS and say it is a requirement, then direct users to configure it by visiting our Enabling Cors guide documentation. Then, a little later down below, we walk the user through the CORS setup explicitly and ignore the previous instructions.

Might be nice to consolidate this information so it isn't mentioned multiple times. If we want to make it explicit and not link off the page, then we should just do that and keep it simple. IMO -- this is the best option, as we're showcasing an example in the guide which is NOT covered in the cors documentation page: enabling a redirect URL.

**Comment by jakubvul-okta** [comment]
This has been fixed in my rewrite.
