### ISSUE TITLE
Python Web Server in Docs

### ISSUE THREAD

**Issue by rdegges** [okta/okta.github.io#1020]
In our widget docs, we show the user how to run a web server using python: https://developer.okta.com/code/javascript/okta_sign-in_widget.html#copy-the-html-to-a-web-server

This is cool, except that only works with python2, which is almost completely dead at this point =0

To make it work, I'd modify the instructions to say that if you're using Python 2, do it that way. If you're using Python 3, the command should be: `python -m http.server`.

**Comment by jakubvul-okta** [comment]
Oh... man I *just* updated this!

**Comment by jakubvul-okta** [comment]
Fixed.
