### ISSUE TITLE
No "embedded resources" related to User Model?

### ISSUE THREAD

**Issue by haishengwu-okta** [okta/okta.github.io#112]
`User Model -> User Properties -> _embedded` has following link but it does't point to anywhere.

http://developer.okta.com/docs/api/resources/users.html#embedded-object

**Comment by karlmcguinness-okta** [comment]
Can you submit a PR with a fix?  I don't think we currently have an embedded resources for User API yet but its part of HAL spec so we can just remove the link

**Comment by haishengwu-okta** [comment]
please review https://github.com/okta/okta.github.io/pull/114
thanks.
