### ISSUE TITLE
SAML 2.0 not available after clicking "Create New App"

### ISSUE THREAD

**Issue by Mark-Hetherington** [okta/okta.github.io#1228]
According to https://developer.okta.com/standards/SAML/setting_up_a_saml_application_in_okta after clicking “Add Applications”, then “Create New App”, I should have a "SAML 2.0" option. However this appears to be out of date, and now the options "Native", "SPA", "Web" and "Service" appear. Presuming SAML 2.0 might be under "Web" I selected that, but there are no options pertaining to SAML.

I assume SAML 2.0 is deprectated as far as OKTA is concerned? I'm undsure how to update the documentation to reflect this.

**Comment by jmelberg-okta** [comment]
Hey @Mark-Hetherington. Our Developer Edition UI does not have the ability to create a SAML application yet, so you'll need to use the old UI to create a SAML application.

On the top-left of the page, you should see a drop-drown to toggle between the new Developer Edition and Classic UI.

**Comment by Mark-Hetherington** [comment]
Thanks @jmelberg-okta, that does explain the discrepancy I'm seeing. I'll make a note of that in and lodge a pull request.

**Comment by jmelberg-okta** [comment]
@mystiberry-okta Any update on this?

**Comment by mystiberry-okta** [comment]
Change is approved in https://github.com/okta/okta.github.io/pull/1229

**Comment by jmelberg-okta** [comment]
Closing due to @1229.

Thanks again for the PR @Mark-Hetherington! 👍
