### ISSUE TITLE
Missing Link to Widget on Docs Landing Page

### ISSUE THREAD

**Issue by rdegges** [okta/okta.github.io#1291]
If you visit https://developer.okta.com/ you'll notice that there is no way to find the widget. I think the solution is to add a Javascript icon box near the top which represents the widget.

It would be very hard for a new user to find the widget given the current linkage.

**Comment by jmelberg-okta** [comment]
@alexdahl-okta: Any suggestions here?

@rdegges: We do have a `JS` icon listed on the [product page](https://developer.okta.com/product), but I agree it is difficult to find the widget w/o using the search bar.

**Comment by rdegges** [comment]
Yah -- the product page is insufficient. We need to get it on the home page stat. Losing a lot of viewers.

I propose we just drop a JS icon in there much like the existing node one as a quick fix.

**Comment by alexdahl-okta** [comment]
We're planning a revamp of language pages, which should make this better and include JS on the docs front page. But, no ETA.

I know @nbarbettini has opinions.

If we add JS to the docs front page soon, we should also make some changes to the JS page:

- change the quick start link to the sign in widget, perhaps https://developer.okta.com/quickstart/#/widget/nodejs/generic
- consider a better sample app, perhaps the simple code from https://developer.okta.com/code/javascript/okta_sign-in_widget
- change the JavaScript SDK section title to "Sign-In Widget" and remove the description
- change the More Resources section title to "JavaScript SDK", change the quick start link label to "JS SDK Tutorial", change the reference link label to "JS SDK Reference", and add a link to "JS SDK Source"

**Comment by jmelberg-okta** [comment]
Fixed with #1447
