### ISSUE TITLE
Documentation Not Up To Date

### ISSUE THREAD

**Issue by rdegges** [okta/okta.github.io#1293]
The Widget documentation is not consistent/up-to-date everywhere. I'm trying to build an app right now and I'm running into confusing issues.

The first is that on the Widget Reference Docs (https://developer.okta.com/code/javascript/okta_sign-in_widget_ref.html), it shows using 1.6.0 of the widget everywhere.

Compare this to the authentication quick start guide (https://developer.okta.com/quickstart/#/widget/nodejs/generic) which shows 2.1.0.

We should probably at least make sure these are consistent since the user is required to use both of them in order to figure anything out.

**Comment by jmelberg-okta** [comment]
The page in reference is being pulled directly from the README of the Sign-In Widget Repo. This will be solved with this PR: https://github.com/okta/okta-signin-widget/pull/288

**Comment by rdegges** [comment]
Makes sense! Closing this as it is redundant now.
