### ISSUE TITLE
Developer blog has too much space when code listings exist in a list

### ISSUE THREAD

**Issue by mraible** [okta/okta.github.io#1305]
See https://developer.okta.com/blog/2017/06/20/develop-microservices-with-jhipster#run-with-kubernetes-and-minikube.

![image](https://user-images.githubusercontent.com/17892/30924425-eb5bf5ca-a36b-11e7-8975-51f8545b537a.png)

Another issue I noticed is that clicking on the link above still hides the heading.

**Comment by jmelberg-okta** [comment]
Fixed with #1469
