### ISSUE TITLE
Whitespace for code blocks regressed to include a bunch of padding / margin

### ISSUE THREAD

**Issue by omgitstom** [okta/okta.github.io#1543]
Looks like the website regressed to include a bunch of unnecessary white space.

Original PR:
https://github.com/okta/okta.github.io/pull/1463

We need to reapply the changes.

**Comment by bretterer** [comment]
I am not seeing any "unnecessary whitespace"

<img width="963" alt="screen shot 2017-12-07 at 12 34 11 pm" src="https://user-images.githubusercontent.com/1906920/33729257-0b3accf6-db4b-11e7-9505-6bcfe052ce06.png">

**Comment by bretterer** [comment]
Not a regression, the PR you reference only fixed for blog posts... if we need this copied over to the api-referrence, we need to possibly add the same to `.PageContent-main pre`
