### ISSUE TITLE
Refresh instructions mention code flow twice

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta.github.io#1570]
The refresh token instructions [here](https://developer.okta.com/authentication-guide/tokens/refreshing-tokens#how-to-get-a-refresh-token) mention the Authorization Code flow twice:

![image](https://user-images.githubusercontent.com/7525482/34228350-37da959a-e585-11e7-95cc-e446be01d15a.png)

It looks like maybe the second section was originally about Client Credentials and Password, but it was changed later.

**Comment by jmelberg-okta** [comment]
Fixed with #1574
