### ISSUE TITLE
Create Claims Groups Field Cannot Be Left Blank

### ISSUE THREAD

**Issue by leebrandt** [okta/okta.github.io#1594]
in https://developer.okta.com/authentication-guide/implementing-authentication/set-up-authz-server#create-claims-optional if I choose groups it says, " If you leave it blank, all users are specified for this claim." but the field cannot be left blank...

**Comment by nbarbettini** [comment]
Confirmed, you can't save the new claim with a blank Filter:

![image](https://user-images.githubusercontent.com/7525482/34588338-4e47fede-f161-11e7-8064-c56afea0d5e6.png)

**Comment by jakubvul** [comment]
@jmelberg-okta https://oktainc.atlassian.net/browse/OKTA-154908

**Comment by jmelberg-okta** [comment]
Seems like the quick fix here is just to remove that text.

**Comment by jakubvul** [comment]
Fixed here: https://github.com/okta/okta.github.io/pull/1718
