### ISSUE TITLE
Specify which OAuth 2.0 endpoints can omit the `client_secret`

### ISSUE THREAD

**Issue by jmelberg-okta** [okta/okta.github.io#1595]
For public clients, you can omit the `client_secret` for token authentication. It is specified under [the revocation endpoint](https://developer.okta.com/docs/api/resources/oauth2#request-parameters-3), but not the introspection endpoint.

**Comment by mystiberry-okta** [comment]
Please create JIRA. I need a single funnel for incoming issues where possible.

**Comment by jmelberg-okta** [comment]
Fixed with #1742
