### ISSUE TITLE
This request and response don't seem to make sense

### ISSUE THREAD

**Issue by gabrielsroka** [okta/okta.github.io#171]
Convert a User to a Federated User

http://developer.okta.com/docs/api/resources/users.html#request-example-convert-a-user-to-a-federated-user

do you use `provider` in the URL string? it's not defined here:
http://developer.okta.com/docs/api/resources/users.html#request-parameters-10

is it a boolean? an enum? is it `FEDERATED` or `FEDERATION`? the doc says `provider in the Provider Object`, but the example doesn't use a Provider Object.

also, would the response have a resetPasswordUrl if they've been converted to Federated?

**Comment by joelfranusic-okta** [comment]
@karlmcguinness-okta can you chime in here?

**Comment by gabrielsroka** [comment]
@joelfranusic-okta  @karlmcguinness-okta any thoughts?

**Comment by vijetmahabaleshwar-okta** [comment]
Just chiming in this conversation - 

"do you use provider in the URL string?"
It seems like the example is using it in the URL string with query parameter "provider=federated"

curl -v -X POST \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "Authorization: SSWS ${api_token}" \
"https://${org}.okta.com/api/v1/users/00ub0oNGTSWTBKOLGLNR/lifecycle/reset_password?**provider=FEDERATED**&sendEmail=false"

"also, would the response have a resetPasswordUrl if they've been converted to Federated?"
Federated users don't support password or recovery_question credential as they are authenticated via a trusted Identity Provider. (http://developer.okta.com/docs/api/resources/users.html#provider-object)

**Comment by jmelberg-okta** [comment]
Closing this issue as its become stale. Please reopen if the problem persists.
