### ISSUE TITLE
Incorrect validation options for Access Token in .NET guide

### ISSUE THREAD

**Issue by jmelberg-okta** [okta/okta.github.io#1780]
As noted [here](https://developer.okta.com/code/dotnet/jwt-validation#additional-validation-for-access-tokens), the `cid` value is listed as "optional", but must be checked when validating an access token. 

> You can also optionally verify that the cid claim matches the expected Client ID of the current application. You’ll have to perform this check after the ValidateToken method returns a validated token

Reference: [Validating Access Tokens](https://developer.okta.com/authentication-guide/tokens/validating-access-tokens#verify-the-claims)

**Comment by bdemers** [comment]
NOTE: validating this field is a `SHOULD` but the doc needs show how to perform this.
We may need to close this one and update the `validating access tokens` page with `SHOULD` and `MUST` notation

**Comment by nbarbettini** [comment]
Thanks for validating (ha) these, @jmelberg-okta. My new PR fixes the language around `cid`.
