### ISSUE TITLE
AuthN API doc does NOT contain a leading `/` in headings when displaying path

### ISSUE THREAD

**Issue by bdemers** [okta/okta.github.io#1829]
Our other doc pages always start with `/api/v1/...`  the AuthN page shows examples as `api/v1/authn/credentials/change_password`
https://developer.okta.com/docs/api/resources/authn#change-password

**Comment by jmelberg-okta** [comment]
To ensure this gets picked up in the future - we should be checking for the preceding `/` [here](https://github.com/okta/okta.github.io/blob/source/scripts/helpers.sh#L20).

**Comment by bdemers** [comment]
Is that currently getting run?

**Comment by jmelberg-okta** [comment]
Yep. This gets picked up on the `npm run post-build-lint` command.

**Comment by bdemers** [comment]
I guess I'm confused.  Is it currently failing then?  The `authn` page is missing the leading slash

**Comment by jmelberg-okta** [comment]
Sorry - I should have been more specific. Our tests right now look for `auth/v` in an API tag element. To ensure the `/` is picked up, we need to change:

`grep -v api/v` to `grep -v /api/v`

**Comment by jmelberg-okta** [comment]
Fixed with #1903
