### ISSUE TITLE
Missing link to initial script for CRUD spec

### ISSUE THREAD

**Issue by yoda** [okta/okta.github.io#1879]
Link to this url seems to be missing
https://developer.okta.com/standards/SCIM/SCIMFiles/Initial_Script_CRUD.txt

**Comment by jmelberg-okta** [comment]
Good catch @yoda! We've added this into the proper place in our documentation.

**Comment by fericsepi** [comment]
> Good catch @yoda! We've added this into the proper place in our documentation.

Do you have a link please?
This doc doesn't seem to list that link https://www.okta.com/resources/whitepaper/scim-provisioning-with-oktas-lifecycle-management/#step-3-submit-for-okta-review-and-testing-29
