### ISSUE TITLE
Wrong OpenIdConnectRequestType in ASP.NET MVC 4.x Quickstart

### ISSUE THREAD

**Issue by leebrandt** [okta/okta.github.io#1881]
In the `Notifications` setting for the `OpenIdConnectAuthenticationOptions` it has

`if (context.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)`

it should be

`if (context.ProtocolMessage.RequestType == OpenIdConnectRequestType.Logout)`

The sample code in GitHub is right, just the docs.

**Comment by nbarbettini** [comment]
Thanks Lee, fixed 👍
