### ISSUE TITLE
React Quickstart missing essential step

### ISSUE THREAD

**Issue by mraible** [okta/okta.github.io#1961]
From https://devforum.okta.com/t/react-integration-example-logout-issue/534/11. The following method is missing in the quickstart:

```
componentDidUpdate() {
   this.checkAuthentication();
}
```

This exists in https://developer.okta.com/code/react/okta_react.html, but not in
https://developer.okta.com/quickstart/#/react/nodejs/express.

**Comment by jmelberg-okta** [comment]
Closing due to being resolved in a prior release.
