### ISSUE TITLE
iOS Swift Notes

### ISSUE THREAD

**Issue by rdegges** [okta/okta.github.io#2001]
In quickstart: https://developer.okta.com/quickstart/#/ios/java/generic

- When creating a new Okta.plist we should explicitly mention that we need the user to substitute in values, it's easy to miss
- For the appdelegate code, we should use Swift 4 syntax which removes the leading `url:` property name. `resume(url, options: options)`
- Whenever we say  `OktaAuth.tokens`, but `tokens` is optional, we have to say `OktaAuth.tokens?`

Feedback from Okta LA hackathon attendee.

**Comment by jmelberg-okta** [comment]
Feedback captured and filed as action items internally. Thanks!
