### ISSUE TITLE
React.js authentication quick start: Unhandled Rejection (TypeError): this.props.login is not a function

### ISSUE THREAD

**Issue by Endymion1977** [okta/okta.github.io#2253]
The default React authentication quick start code does not work out of the box. If you follow these instructions: https://developer.okta.com/quickstart/#/react/nodejs/generic and just copy the code verbatim, you will get an error:

`Unhandled Rejection (TypeError): this.props.login is not a function`

It looks like you need to change:

```
async login() {
    // Redirect to ‘/’ after login
    this.props.login(‘/’);
}

async logout() {
    // Redirect to ‘/’ after logout
    this.props.logout(‘/’);
}
```

to 

```
async login() {
    // Redirect to ‘/’ after login
    this.props.auth.login(‘/’);
}

async logout() {
    // Redirect to ‘/’ after logout
    this.props.auth.logout(‘/’);
}
```

**Comment by jmelberg-okta** [comment]
Resolved with #2520
