### ISSUE TITLE
Code samples on https://okta.github.io/code/python/ are 404s

### ISSUE THREAD

**Issue by mraible** [okta/okta.github.io#2403]
If you're logged in as a member of the Okta org, the repos work fine. For others, they get a 404. We should remove the links or restore public access for the repos.

**Comment by jmelberg-okta** [comment]
`https://okta.github.io` hosts an outdated version of our developer site. We should look to remove all content there, and in the `master` branch.

@robertjd & @nbarbettini ^

**Comment by bretterer** [comment]
This should be resolved now that the repo is public
