### ISSUE TITLE
[documentation] Identity provider user model is missing Credentials object

### ISSUE THREAD

**Issue by andriyko** [okta/okta.github.io#241]
According to [User properties](http://developer.okta.com/docs/api/resources/users.html#user-properties) the `credentials` attribute is required and should be present in every user object, correct?
The `credentials` property  is missing in [Identity provider user model](http://developer.okta.com/docs/api/resources/idps#identity-provider-user-model). I would expect it to be present with [provider type](http://developer.okta.com/docs/api/resources/users.html#provider-object) `FEDERATION` (or `SOCIAL`?).

**Comment by joelfranusic-okta** [comment]
@mystiberry-okta is this something you could help with?

**Comment by mystiberry-okta** [comment]
Absolutely. Will follow up to either add it to provider type or verify that it isn't there and note in User properties doc. Thanks for this issue!

**Comment by jmelberg-okta** [comment]
The documentation has been significantly updated since this was filed. If there is still confusion around this topic - please update the description and reopen.
