### ISSUE TITLE
Blog posts on https://developer.okta.com/code/react/ should be formatted as a list

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta.github.io#2455]
The blog post links on the React page should be formatted as a list like other code pages, not as a paragraph.

<img width="952" alt="react" src="https://user-images.githubusercontent.com/26014482/47890113-813e4a00-ddf1-11e8-9f76-2e0dd95bfda6.png">

**Comment by jmelberg-okta** [comment]
Resolved with #2476
