### ISSUE TITLE
Spring Boot Security SAML

### ISSUE THREAD

**Issue by ulisesbocchio** [okta/okta.github.io#250]
Not really a problem, just saw your Spring Security SAML sample app and wanted to share this Spring Boot demo app with SAML SSO through OKTA, using an open source plugin that avoids the boiler plate of Spring Security SAML, check it out here: https://github.com/ulisesbocchio/spring-boot-security-saml/tree/master/spring-boot-security-saml-demo-okta.

**Comment by joelfranusic-okta** [comment]
Thanks!

**Comment by joelfranusic-okta** [comment]
@ulisesbocchio - sorry for the late reply. This looks cool, I see that you're keeping this (and related) GitHub repositories updated. I'll see if we can get this added to our website.
