### ISSUE TITLE
Using variables instead of markdown links

### ISSUE THREAD

**Issue by bretterer** [okta/okta.github.io#2542]
In https://github.com/okta/okta.github.io/blob/source/_source/_code/python/pysaml2.md#overview ,  Is there a reason we are using the code [{{ page.saml_library }}]({{ page.saml_library_url }}) and pulling data from frontmatter instead of standard markdown?

**Comment by jakubvul** [comment]
> Is there a reason

Not that I'm aware of.

**Comment by joelfranusic-okta** [comment]
Gosh, it's been years since I've looked at this. Please accept my general apologies. I _think_ that the reason I did that was a premature optimization. If I recall correctly, I did that because I was expecting to reuse that template for other SAML libraries.

**Comment by joelfranusic-okta** [comment]
For what it's worth, I'll always be in favor of removing stuff that I did on this website. In particular, removing things like variables.
