### ISSUE TITLE
Dead Links in /code/dotnet/

### ISSUE THREAD

**Issue by bretterer** [okta/okta.github.io#2742]
Laura and Lee,

There are a few dead links that need to be addressed.  

FILE: code/dotnet/okta-oauth-spa-authjs-osw/index.md
[✖] https://github.com/oktadeveloper/okta-oauth-spa-authjs-osw
FILE:code/dotnet/okta-oidc-spa-osw-aspnet/index.md
[✖] https://github.com/oktadeveloper/okta-oidc-spa-osw-aspnet

Could you please fix these and merge into source?

**Comment by laura-rodriguez** [comment]
This issue was reported in JIRA: https://oktainc.atlassian.net/browse/OKTA-209821
and fixed by https://github.com/okta/okta.github.io/pull/2728.
