### ISSUE TITLE
version 1.3.3 doesn't work with Angular 1.5.5

### ISSUE THREAD

**Issue by jmichaud-ips** [okta/okta.github.io#333]
I tried adding the sign in widget to my angular website.  I get a digest error: Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [].

I'm able to get the widget working in an Asp.net MVC website, but I prefer to include it in my existing angular website.

**Comment by raphaellondner-okta** [comment]
Hi @jmichaud-ips , thank you for your feedback. We actually have a fully functioning AngularJS sample available at https://github.com/jmelberg/angular-sso-samples . Don't hesitate to reach out to us at developers@okta.com if you run into issue with that code sample!
