### ISSUE TITLE
Subdomain documentation for Postman

### ISSUE THREAD

**Issue by omgitstom** [okta/okta.github.io#688]
http://developer.okta.com/docs/api/getting_started/api_test_client.html

> subdomain: Enter the subdomain, for example myOrg. Do not include ‘-admin’ in the subdomain.

It took me a while to figure out what we were asking for.  subdomain for my domain of my website? subdomain from my email suffix (we are reusing myOrg and myOrg.com maybe you are treating what is left of the tld as the subdomain?) or the subdomain of my okta org?

We need to be explicit on what to put in, I can see this being confusing for anyone that doesn't notice their okta generated domain is prefixed with -admin

**Comment by omgitstom** [comment]
Another question, but what are we even using the subdomain for?  I can't find it in Postman, if we aren't using it, we should remove it.

**Comment by johngronberg-okta** [comment]
@karlmcguinness-okta Looking at our current postman collections, I don't actually see subdomain used in any of the example calls. Do you know why it's in the environment?

**Comment by karlmcguinness-okta** [comment]
You can remove. This dates back many years from my laptop.  We have a hidden `Org` API that some partners use that require this param.

**Comment by johngronberg-okta** [comment]
sounds good. Opened PR #689 to fix.
