### ISSUE TITLE
Okta Signin Widget Simple Example needs a better introduction

### ISSUE THREAD

**Issue by omgitstom** [okta/okta.github.io#824]
```If you are a developer, the best way to understand the Okta Sign-In Widget is to look at a simple example of the HTML needed to get it working. The HTML below shows you how to quickly and easily set up a fully featured login experience:```

Let's start out the example section with actually explaining what the example does.  So I can know what I'm getting into.  Understanding that the example will log me in, and redirect me to the okta product end user dashboard is crucial.

**Comment by jmelberg-okta** [comment]
Updated: #1009
