### ISSUE TITLE
Explaining the Different OpenID Connect Authorization Servers in Okta

### ISSUE THREAD

**Issue by omgitstom** [okta/okta.github.io#841]
Okta has different authorization servers you can use with OpenID Connect.

We need to be ___extremely___ clear in documentation when you would use one versus the other because one is crammed into the OAuth 2.0 section.

I would like to see this information added to the OpenID Connect Authentication Reference, explained up front.

### Okta's Authorization Server
/oauth/v1/

Is useful for extremely limited and simple OIDC use cases.  A developer can validate id_tokens, but not access_tokens with the public key stored in the key endpoint.  If you need to use access_tokens to protect your own APIs, you need to use API Access Management Authorization Server

It can also be used for SSO use cases with Okta, where you need another application to use Okta, and your okta organization for SSO.

This authorization server can not support custom claims or scopes other than `groups` (which will place the groups of the user in a claim)

This authorization server can not support customized `sub` claims.  The sub will always be the okta user id.

### API Access Management Authorization Server
/oauth/{authserverid}/v1/

A full-fledged OpenID connect authorization server that can support custom audiences, scopes, claims, and will allow id_token and access_token validation (client side and server side).  Useful when your application has APIs that need to be protected with an access_token or you have advanced use cases for custom scopes and claims.

The access_token can be validated because the get keys endpoint will have the pub key used to validate the access token.

The `sub` claim can be customized through claim mapping and configuration

**Comment by omgitstom** [comment]
@karlmcguinness-okta anything I'm missing?

**Comment by karlmcguinness-okta** [comment]
It might be too much detail for intro, but its usually a good idea to explain token issuer and audience the relationship to a resource domain.  I think more graphics would be easier on the eyes than lots of text but thats just my preference.

![image](https://cloud.githubusercontent.com/assets/7748666/25998898/f25e8936-371a-11e7-9dde-74f990ae081b.png)

Custom claims for ID Tokens are supported for the Okta AS but not scopes.  Scopes will eventually be for the Okta API.

**Comment by mystiberry-okta** [comment]
ack and thanks!

**Comment by jmelberg-okta** [comment]
Fixed with [OKTA-130473](https://oktainc.atlassian.net/browse/OKTA-130473).
