### ISSUE TITLE
missing import in recent PWA post

### ISSUE THREAD

**Issue by dogeared** [okta/okta.github.io#844]
https://github.com/okta/okta.github.io/blob/master/_source/_posts/2017-05-09-progressive-web-applications-with-angular-and-spring-boot.md

The code following the line `Modify beer.service.ts to call the “good-beers” API service.` should have the following import:

```
import 'rxjs/add/operator/map';
```

NOTE: The github repo has this import, it's just the code example in the blog post that needs to be updated.

**Comment by jmelberg-okta** [comment]
Resolved with #852
