### ISSUE TITLE
 Improve OIDC docs by explaining nonce and state

### ISSUE THREAD

**Issue by bdemers** [okta/okta.github.io#880]
This is a more general TODO, but our OIDC doc could use some work.  I was confused specifically around our description of the `nonce` and `state`.  After brushing up on the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html) these values are clear.  So even a pointer to the spec would be an improvement.

**Comment by dogeared** [comment]
We should also clear up the language in this section: http://developer.okta.com/docs/api/resources/oidc.html#scope-values

The offline_access section is not clear, especially in the context of `grant_type=password` where `response_type=code` is *not* required.

I think it's trying to make the point that hitting `/token` with a `scope=offline_access` must use a code returned from a previous `/authorize` call that had `response_type=code`

**Comment by jmelberg-okta** [comment]
@bdemers The page does include a section discussing the *state*:

```
Okta requires the OAuth 2.0 state parameter on all requests to the authorization endpoint in order to prevent cross-site request forgery (CSRF). The OAuth 2.0 specification requires that clients protect their redirect URIs against CSRF by sending a value in the authorize request which binds the request to the user-agent’s authenticated state. Using the state parameter is also a countermeasure to several other known attacks as outlined in OAuth 2.0 Threat Model and Security Considerations.
```
