### ISSUE TITLE
http://developer.okta.com/blog redirects to https://okta.github.io/blog/

### ISSUE THREAD

**Issue by mraible** [okta/okta.github.io#903]
It should redirect to https://developer.okta.com/blog.

http://developer.okta.com redirects to http://developer.okta.com properly and clicking on the "Blog" link at the bottom works.

**Comment by rchild-okta** [comment]
Thanks @mraible - we're looking into this today. To confirm - when you click the "blog" link at the bottom of the page, it does **not** redirect you to https://developer.okta.com/blog/ <-- note trailing slash? If not, which page are you seeing this on?

The trailing slash diff in behavior is something we saw last night when moving to TLS and cloudfront - we did a temporary fix to move most of our URL's over (although, not all), but today we're looking into how we can get the original URL's working.

**Comment by mraible** [comment]
The "blog" link works and it redirects me to HTTPS with the trailing / - https://developer.okta.com/blog/

Entering http://developer.okta.com/blog is what causes the redirect to okta.github.io. If I enter http://developer.okta.com/blog/, it redirects properly to HTTPS.

**Comment by jmelberg-okta** [comment]
Seems like this issue has been resolved.

**Comment by jmelberg-okta** [comment]
We've been able to fix a large number of these redirects. If another comes up, please reopen this issue.
