### ISSUE TITLE
User.activated is nullable

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta.github.io#917]
I was looking at the User model definition here: https://developer.okta.com/docs/api/resources/users.html#user-model

It states that `User.activated` is not nullable. However, retrieving a typical user from my org gives me:

```json
{
   "id":"00u9o1nikjvOBg5Zo0h7",
   "status":"ACTIVE",
   "created":"2017-02-22T02:33:02.000Z",
   "activated":null,
   "statusChanged":"2017-02-22T17:50:43.000Z",
   <snip>
}
```

Does the documentation need to be updated?

**Comment by jmelberg-okta** [comment]
Fixed with: #973
