### ISSUE TITLE
Malformed link in blog post

### ISSUE THREAD

**Issue by alexdahl-okta** [okta/okta.github.io#993]
The [Build a React Application with User Authentication in 15 Minutes](https://developer.okta.com/blog/2017/03/30/react-okta-sign-in-widget) post has a malformed link under "Add the OpenID Connect Application in Okta".

https://github.com/okta/okta.github.io/blame/master/_source/_posts/2017-03-30-react-okta-sign-in-widget.md#L78

<img width="682" alt="screen shot 2017-06-27 at 4 23 29 pm" src="https://user-images.githubusercontent.com/26014482/27617971-4c69484a-5b55-11e7-92e1-d5f3d9bf0649.png">

**Comment by jmelberg-okta** [comment]
Fixed with #1004
